[project]
name = "hugh"
dynamic = ["version"]
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "psutil>=7.1.3",
    "semantic-version>=2.10.0",
    "tomlkit>=0.13.3",
    "readerwriterlock>=1.0.9",
    "watchfiles>=1.1.1",
    "xxjson>=0.2.0",
    "httpx>=0.28.1",
    "polib>=1.2.0",
    "jsonschema>=4.25.1",
]

[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8", "polib"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "_version.py"
