from typing import Protocol


class Config(Protocol):
    def get(self, key, default=None): ...
    def set(self, key, value): ...
    def delete(self, key): ...
    def keys(self): ...
    def items(self): ...
